### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by sapegin** [tarruda/grunt-exec-jshint#1]
Why you wrote new plugin instead of using [grunt-contrib-jshint](https://github.com/gruntjs/grunt-contrib-jshint)?

**Comment by tarruda** [comment]
Very simple, the grunt-contrib-jshint task do not support directory-level .jshintrc. My editor(and probably every other editor) uses directory jshintrc to highlight errors so I cannot use grunt-contrib-jshint.

At first I tought about sending a pull request, but after reading through their issues I already found the issue and it was closed without fixing.

**Comment by sapegin** [comment]
It works fine with .jshintrc in project root, for example.

**Comment by tarruda** [comment]
Not if I want to have a separate jshint for the tests.

For example, I often use the 'chai' assertion library which uses getters to verify assertions:

expect(x).to.be.true;

By the default this is forbidden by jshint, but I want to override that behavior in tests and its not  possible with grunt-contrib-jshint
